//public/Items.json
export const data_cou = {
  bootstrap: [
    {
      id: 1,
      title: "Cầu lông 1",
      body: "Cầu lông 1",
      imageUrl: "/cou/a1.jpg",
      docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
    },
    {
      id: 2,
      title: "City Views",
      body: "Bootstrap Carousel Example",
      imageUrl: "/cou/a2.jpg",
      docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
    },
    {
      id: 3,
      title: "Wild Life",
      body: "Bootstrap Carousel Example",
      imageUrl: "/cou/a3.jpg",
      docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
    },
    {
      id: 4,
      title: "Foods and Culture",
      body: "Bootstrap Carousel Example",
      imageUrl: "/cou/a4.jpg",
      docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
    },
  ],
};

export const provinces = [
  "Hà Nội",
  "Vĩnh Phúc",
  "Bắc Ninh",
  "Quảng Ninh",
  "Hải Dương",
  "Hải Phòng",
  "Hưng Yên",
  "Thái Bình",
  "Hà Nam",
  "Nam Định",
  "Ninh Bình",
  "Hà Giang",
  "Cao Bằng",
  "Bắc Kạn",
  "Tuyên Quang",
  "Lào Cai",
  "Yên Bái",
  "Thái Nguyên",
  "Lạng Sơn",
  "Bắc Giang",
  "Phú Thọ",
  "Điện Biên",
  "Lai Châu",
  "Sơn La",
  "Hoà Bình",
  "Thanh Hoá",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thừa Thiên Huế",
  "Đà Nẵng",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Khánh Hoà",
  "Ninh Thuận",
  "Bình Thuận",
  "Kon Tum",
  "Gia Lai",
  "Đắk Lắk",
  "Đắk Nông",
  "Lâm Đồng",
  "Bình Phước",
  "Tây Ninh",
  "Bình Dương",
  "Đồng Nai",
  "Bà Rịa - Vũng Tàu",
  "TP.Hồ Chí Minh",
  "Long An",
  "Tiền Giang",
  "Bến Tre",
  "Trà Vinh",
  "Vĩnh Long",
  "Đồng Tháp",
  "An Giang",
  "Kiên Giang",
  "Cần Thơ",
  "Hậu Giang",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
];

export const rank = [
  "Trung Bình - Khá",
  "Tốt - Xuất sắc",
  "Yếu - Tốt",
  "Khá - Tốt",
];
export const Gioitinh = ["Cả nam và nữ", "Nữ", "Nam"];
